version: '2'
services:
    schmongoblog-app:
        image: schmongoblog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://schmongoblog-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=SchmongoBlog
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    schmongoblog-mongodb:
        extends:
            file: mongodb.yml
            service: schmongoblog-mongodb
